# Generated by Django 2.2.1 on 2019-08-09 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp2', '0005_auto_20190805_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='num',
            field=models.CharField(max_length=15),
        ),
    ]
