# Generated by Django 2.2.4 on 2019-08-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20190809_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phonenum',
            field=models.IntegerField(),
        ),
    ]
