# Generated by Django 2.2.4 on 2019-08-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20190809_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='store_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='store',
            name='locate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='client',
            name='my_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='client',
            name='phonenum',
            field=models.IntegerField(default=0),
        ),
    ]
