# Generated by Django 2.2.2 on 2019-08-29 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20190809_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='store_num',
        ),
        migrations.AddField(
            model_name='client',
            name='store',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='store.Store'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='recent_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='client',
            name='phonenum',
            field=models.CharField(max_length=10),
        ),
    ]
